name: un_doc_url_crawl
description: un_doc_url_crawl
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  args: ^2.0.0

  html: ^0.15.4

  puppeteer: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
